# Permalinks
permalink:        pretty
# following line dropped in order to set up running jekyll v3.0
# relative_permalinks: true

# Setup
title:            Kirgsn
tagline:          'Machine Learning Blog'
description:      'Sharing insights I gathered on my journey to Data Science and Machine Learning'
url:              https://github.com/wkirgsn
baseurl:          /

#theme: jekyll-theme-modernist


# paginator
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

paginate:         5

# Custom cars
github:
  owner_url:      https://github.com/wkirgsn
  owner_name:     WKirgsn
  repository_url: https://github.com/wkirgsn/wkirgsn.github.io
  

author:
  name:           'Wilhelm Kirchgaessner'
  url:            https://github.com/wkirgsn

show_downloads: true
#google_analytics:

